survey/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("create/", views.create_poll, name="create"),
    path("<int:question_id>/update/", views.update_poll, name="update"),
    path("<int:question_id>/delete/", views.delete_poll, name="delete"),
]

survey/survey/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("polls.urls")),
]

survey/polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

survey/polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django import forms

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "Choix invalide! Il faut faire un choix avant de soumettre.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["question_text"]


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ["choice_text"]


ChoiceFormSet = forms.inlineformset_factory(
    Question, Choice, form=ChoiceForm, extra=1, can_delete=True
)


def create_poll(request):
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        choice_forms = [
            ChoiceForm(request.POST, prefix=str(x))
            for x in range(int(request.POST.get("choice_count", 0)))
        ]

        if question_form.is_valid() and all([cf.is_valid() for cf in choice_forms]):
            question = Question.objects.create(
                question_text=question_form.cleaned_data["question_text"],
                pub_date=timezone.now(),
            )
            for cf in choice_forms:
                Choice.objects.create(
                    question=question, choice_text=cf.cleaned_data["choice_text"]
                )
            return redirect("polls:index")
    else:
        question_form = QuestionForm()
        choice_forms = [ChoiceForm(prefix="0")]

    return render(
        request,
        "polls/create.html",
        {"question_form": question_form, "choice_forms": choice_forms},
    )


def update_poll(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        formset = ChoiceFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect("polls:detail", pk=question.id)
    else:
        form = QuestionForm(instance=question)
        formset = ChoiceFormSet(instance=question)
    return render(
        request,
        "polls/update.html",
        {"form": form, "formset": formset, "question": question},
    )


def delete_poll(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        question.delete()
        return redirect("polls:index")
    return render(request, "polls/delete.html", {"question": question})

survey/polls/templates/polls/create.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

<div class="polls">
  <h1 class="titre">Créer un nouveau sondage</h1>

  <form method="post" class="polls-form" id="polls-form">
    {% csrf_token %} {{ question_form.as_p }}
    <div id="choices">
      {% for choice_form in choice_forms %}
      <div class="choice-form">{{ choice_form.as_p }}</div>
      {% endfor %}
    </div>
    <button type="button" id="add-choice" class="btn-add">
      Ajouter un choix
    </button>
    <input
      type="hidden"
      name="choice_count"
      id="choice-count"
      value="{{ choice_forms|length }}"
    />
    <button type="submit" class="btn-submit">Créer le sondage</button>
  </form>

  <a href="{% url 'polls:index' %}" class="btn-back">Retour à la liste</a>
</div>

<script src="{% static 'polls/js/create_poll.js' %}"></script>

survey/polls/templates/polls/delete.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

<div class="polls-container">
  <h1 class="poll-question">Supprimer le sondage</h1>

  <div class="delete-confirmation">
    <p class="confirmation-message">
      Êtes-vous sûr de vouloir supprimer le sondage :
      <strong>"{{ question.question_text }}"</strong> ?
    </p>

    <p class="warning-message">
      Cette action est irréversible et supprimera également tous les choix et
      votes associés.
    </p>
  </div>

  <form method="post" class="delete-form">
    {% csrf_token %}
    <div class="form-actions">
      <button type="submit" class="action-button delete-button">
        Confirmer
      </button>
      <a href="{% url 'polls:index' %}" class="action-button cancel-button"
        >Annuler</a
      >
    </div>
  </form>
</div>

survey/polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}" />
<div class="polls-container">
  <div class="navigation-buttons">
    <a href="{% url 'polls:index' %}" class="action-button back-button"
      >Liste</a
    >
  </div>
  <h1 class="poll-question">{{ question.question_text }}</h1>
  <form
    action="{% url 'polls:vote' question.id %}"
    method="post"
    class="poll-form"
  >
    {% csrf_token %} {% if error_message %}
    <p class="error-message"><strong>{{ error_message }}</strong></p>
    {% endif %}
    <div class="choices-container">
      {% for choice in question.choice_set.all %}
      <div class="choice-item">
        <input
          type="radio"
          name="choice"
          id="choice{{ forloop.counter }}"
          value="{{ choice.id }}"
          class="choice-input"
        />
        <label for="choice{{ forloop.counter }}" class="choice-label">
          {{ choice.choice_text }}
        </label>
      </div>
      {% endfor %}
    </div>
    <button type="submit" class="vote-button">Soumettre</button>
  </form>
</div>

survey/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

<div class="polls-container">
  <h1 class="polls-title">Mes sondages</h1>

  <a href="{% url 'polls:create' %}" class="action-button create-button"
    >Créer</a
  >

  {% if latest_question_list %}
  <ul class="polls-list">
    {% for question in latest_question_list %}
    <li class="poll-item">
      <div class="poll-info">
        <a href="{% url 'polls:detail' question.id %}" class="poll-link"
          >{{ question.question_text }}</a
        >
        <span class="poll-date"
          >Publié le {{ question.pub_date|date:"d M Y à H:i" }}</span
        >
      </div>
      <div class="poll-actions">
        <a
          href="{% url 'polls:update' question.id %}"
          class="action-button update-button"
          >Modifier</a
        >
        <a
          href="{% url 'polls:delete' question.id %}"
          class="action-button delete-button"
          >Supprimer</a
        >
      </div>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p class="no-polls">Aucun sondage n'est disponible pour le moment.</p>
  {% endif %}
</div>

survey/polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

<div class="results-container">
  <h1 class="question-title">{{ question.question_text }}</h1>

  <ul class="choice-list">
    {% for choice in question.choice_set.all %}
    <li class="choice-item">
      <div class="choice-text">{{ choice.choice_text }}</div>
      <div class="vote-bar-container">
        <div
          class="vote-bar"
          style="width: {% widthratio choice.votes question.choice_set.count 100 %}%;"
        ></div>
      </div>
      <div class="vote-count">
        {{ choice.votes }} vote{{ choice.votes|pluralize }}
      </div>
    </li>
    {% endfor %}
  </ul>
  <div class="form-actions">
    <a href="{% url 'polls:detail' question.id %}" class="vote-again-btn"
      >Voter encore</a
    >
    <a href="{% url 'polls:index' %}" class="action-button cancel-button"
      >Liste</a
    >
  </div>
</div>

survey/polls/templates/polls/update.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

<div class="polls">
  <h1 class="titre">Mettre à jour le sondage</h1>

  <form method="post" class="polls-form">
    {% csrf_token %} {{ form.as_p }}
    <br />
    {{ formset.management_form }} {% for choice_form in formset %}
    <div class="choice-form">{{ choice_form.as_p }}</div>
    {% endfor %}
    <button type="submit" class="btn-submit">Mettre à jour</button>
  </form>

  <a href="{% url 'polls:index' %}" class="btn-back">Annuler</a>
</div>

<script src="{% static 'polls/js/update_poll.js' %}"></script>